name: mwani
description: HRMS app.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^1.2.2
  provider: ^6.0.2
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  firebase_core: ^1.12.0
  get_it: ^7.2.0
  json_annotation: ^4.4.0
  page_transition: ^2.0.5
  shared_preferences: ^2.0.13
  permission_handler: ^9.0.2
  jiffy: ^5.0.0
  google_fonts: 2.2.0
  simple_animations: ^4.0.1
  fluttertoast: ^8.0.8
  flutter_spinkit: ^5.1.0
  flutter_rounded_date_picker: ^2.0.2
  flutter_svg: ^1.0.3
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^9.2.0
  photo_manager: ^1.3.10
  photo_view: ^0.13.0
  uuid: ^3.0.5
  intl: ^0.17.0
  image_cropper: ^1.4.1
  nanoid: ^1.0.0
  image_picker: ^0.8.4+9
  shimmer: ^2.0.0
  pie_chart: ^5.3.0
  month_picker_dialog: ^0.4.0
  motion_toast: ^2.1.6
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  sembast: ^3.2.0
  sembast_web: ^2.0.1+1
  dio: ^4.0.6
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.0
  dotted_border: ^2.0.0+2
  percent_indicator: ^4.0.1
  card_swiper: ^2.0.3
  open_file: ^3.2.1
  file_picker: ^4.5.1
  webview_flutter: ^3.0.4
  rename: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  flutter_launcher_icons:
    git:
      url: https://github.com/Davenchy/flutter_launcher_icons.git
      ref: fixMinSdkParseFlutter2.8

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo/
    - assets/images/auth/
    - assets/images/flag/
    - assets/images/onboard/
    - assets/images/bottombar/
    - assets/images/common/
    - assets/images/home/
    - assets/images/drawer/
    - assets/images/loan/
    - assets/images/file/
    - assets/lottie/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/fonts/Calibri/Calibri.ttf
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham/GothamMedium.ttf
    - family: GothamRounded
      fonts:
        - asset: assets/fonts/GothamRounded/GothamRMedium.otf
    - family: AdobeArabic
      fonts:
        - asset: assets/fonts/AdobeArabic/AdobeArabic-Regular.otf
    - family: DinarTwo
      fonts:
        - asset: assets/fonts/DinarTwo/GEDinarM.otf
